#!/usr/bin/env bash

#
# 清理家目录中的垃圾文件、历史记录
#

# APP Disable/Enable Rule Directory
PATH_DISABLE="$HOME/*******/*******/HOME-Cleaner/app.disable"
PATH_ENABLE="$HOME/*******/*******/HOME-Cleaner/app.enable"

# 单一文件 (Single File)
Single_File() {
    echo -e "$1" | awk -F '^SF\\|\\|' '{print $2}' |
    while read -r SF; do
        if [[ -f "$SF" ]]; then
            rm -rf "$HOME/$SF"
        fi
    done
}

# 多个规律文件 (Rule File)
Rule_File() {
    echo -e "$1" | awk -F '^RF\\|\\|' '{print $2}' |
    while read -r RF; do
        ls "$HOME"/`echo -e "$RF" | sed 's/\ /\\\ /g'` 2>/dev/null | cat | while read -r RF2SF; do
            rm -rf "$RF2SF"
        done
    done
}

# 只删目录 (DeleteOnly Dir)
Deleteonly_Dir() {
    echo -e "$1" | awk -F '^DD\\|\\|' '{print $2}' |
    while read -r DD; do
        if [[ -d "$DD" ]]; then
            rm -rf "$HOME/$DD"
        fi
    done
}

# 需重建目录 (Recreate Dir)
Recreate_Dir() {
    echo -e "$1" | awk -F '^RD\\|\\|' '{print $2}' |
    while read -r RD; do
        if [[ -d "$RD" ]]; then
            rm -rf "$HOME/$RD"
            mkdir -p "$HOME/$RD"
        fi
    done
}

# Shell 命令 (Shell Command) (主要用于删除历史记录)
Shell_Command() {
    echo -e "$1" | awk -F '^SC\\|\\|' '{print $2}' |
    while read -r SC; do
        bash -c "$SC" 1>/dev/null 2>&1
    done
}

# 遍历 APP 规则
APP_RULE=$(cat "$PATH_ENABLE"/*)
# 单一文件 (Single File)
SF_RULE=$(echo -e "$APP_RULE" | grep '^SF||')
if [[ "$?" == "0" ]]; then
    Single_File "$SF_RULE"
fi
# 多个规律文件 (Rule File)
RF_RULE=$(echo -e "$APP_RULE" | grep '^RF||')
if [[ "$?" == "0" ]]; then
    Rule_File "$RF_RULE"
fi
# 只删目录 (DeleteOnly Dir)
DD_RULE=$(echo -e "$APP_RULE" | grep '^DD||')
if [[ "$?" == "0" ]]; then
    Deleteonly_Dir "$DD_RULE"
fi
# 需重建目录 (Recreate Dir)
RD_RULE=$(echo -e "$APP_RULE" | grep '^RD||')
if [[ "$?" == "0" ]]; then
    Recreate_Dir "$RD_RULE"
fi
# Shell 命令 (Shell Command) (主要用于删除历史记录)
SC_RULE=$(echo -e "$APP_RULE" | grep '^SC||')
if [[ "$?" == "0" ]]; then
    Shell_Command "$SC_RULE"
fi
